name: flutter_screen_manager_example
description: Example app for flutter_screen_manager plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screen_manager:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter