name: flutter_screen_manager
description: A Flutter plugin to manage the device's screen on Android and iOS.
version: 1.0.0
homepage: https://github.com/clovisnicolas/flutter_screen

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: flutter.plugins.screen.screen
    pluginClass: ScreenPlugin